services:
  webfrontend:
    build: frontend/
    ports:
      # This is the entrypoint to our app
      - 443:443
      -  80:80

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD=flotteLotteUnterwegs
    volumes:
      - mysql/:/docker-entrypoint-initdb.d
